// mockData.ts — Schedule Board PCF Control

export interface Resource {
  id: string;
  name: string;
  initials: string;
  utilization: number;
  bookedHours: string;
}

export interface Requirement {
  id: string;
  name: string;
  duration: string;
  fromDate: string;
  toDate: string;
  territory: string;
  priority: string;
  status: string;
}

export interface Booking {
  id: string;
  resourceId: string;
  title: string;
  type: "Work Order" | "Requirement";
  durationLabel: string;
  // Hourly view: fractional hour (8.0 = 8:00 AM)
  startHour: number;
  endHour: number;
  // Which day index within selected range (0-based, 0=Mon 9/14)
  dayIndex: number;
  // Display label for daily view: "9:00 AM"
  startTimeLabel: string;
  color: "blue" | "light-blue" | "pink" | "dark-blue" | "green" | "grey";
  icon:
    | "clock"
    | "car"
    | "check"
    | "cancel"
    | "coffee"
    | "wrench"
    | "plug"
    | "lightning";
  isDashed?: boolean;
  workOrderId?: string;
  // Duration in decimal hours (used for weekly aggregation)
  durationHours: number;
}

export interface OpenRequirement {
  id: string;
  name: string;
  fromDate: string;
  toDate: string;
  duration: string;
  proposedDuration: string;
  fulfilledDuration: string;
  remaining: string;
  priority: string;
  territory: string;
  status: string;
  createdOn: string;
}

// ─── Resources ────────────────────────────────────────────────────────────────
export const RESOURCES: Resource[] = [
  {
    id: "r1",
    name: "David Smith",
    initials: "DS",
    utilization: 72,
    bookedHours: "5h 42m booked",
  },
  {
    id: "r2",
    name: "Jim Glynn",
    initials: "JG",
    utilization: 45,
    bookedHours: "3h 36m booked",
  },
  {
    id: "r3",
    name: "Maria Campbell",
    initials: "MC",
    utilization: 88,
    bookedHours: "7h 04m booked",
  },
  {
    id: "r4",
    name: "Nancy Anderson",
    initials: "NA",
    utilization: 30,
    bookedHours: "2h 24m booked",
  },
  {
    id: "r5",
    name: "Patrick Sands",
    initials: "PS",
    utilization: 60,
    bookedHours: "4h 48m booked",
  },
  {
    id: "r6",
    name: "Paul Cannon",
    initials: "PC",
    utilization: 0,
    bookedHours: "0m booked",
  },
  {
    id: "r7",
    name: "Rene Valdes",
    initials: "RV",
    utilization: 52,
    bookedHours: "4h 10m booked",
  },
  {
    id: "r8",
    name: "Robert Lyon",
    initials: "RL",
    utilization: 15,
    bookedHours: "1h 12m booked",
  },
  {
    id: "r9",
    name: "Saurabh Raj",
    initials: "SR",
    utilization: 38,
    bookedHours: "3h 02m booked",
  },
];

// ─── Bookings ─────────────────────────────────────────────────────────────────
// dayIndex: 0=Mon 9/14, 1=Tue 9/15, 2=Wed 9/16, 3=Thu 9/17, 4=Fri 9/18, 5=Sat 9/19, 6=Sun 9/20
// For hourly view: startHour/endHour are absolute hours (8.0=8AM, 8.5=8:30AM)
export const BOOKINGS: Booking[] = [
  // David Smith
  {
    id: "b1",
    resourceId: "r1",
    title: "Install Vacuum",
    type: "Requirement",
    durationLabel: "3h 05m",
    startHour: 8.0,
    endHour: 11.083,
    dayIndex: 0,
    startTimeLabel: "8:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00101",
    durationHours: 3.08,
  },
  {
    id: "b2",
    resourceId: "r1",
    title: "Fix Washer",
    type: "Requirement",
    durationLabel: "1h 03m",
    startHour: 9.5,
    endHour: 10.55,
    dayIndex: 1,
    startTimeLabel: "9:30 AM",
    color: "light-blue",
    icon: "wrench",
    workOrderId: "00102",
    durationHours: 1.05,
  },
  {
    id: "b2b",
    resourceId: "r1",
    title: "Site Survey",
    type: "Work Order",
    durationLabel: "2h 00m",
    startHour: 10.0,
    endHour: 12.0,
    dayIndex: 2,
    startTimeLabel: "10:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00110",
    durationHours: 2.0,
  },
  {
    id: "b2c",
    resourceId: "r1",
    title: "HVAC Inspection",
    type: "Work Order",
    durationLabel: "1h 30m",
    startHour: 9.0,
    endHour: 10.5,
    dayIndex: 3,
    startTimeLabel: "9:00 AM",
    color: "light-blue",
    icon: "wrench",
    workOrderId: "00115",
    durationHours: 1.5,
  },

  // Jim Glynn
  {
    id: "b3",
    resourceId: "r2",
    title: "Buy and Deliver Parts",
    type: "Requirement",
    durationLabel: "1h 44m",
    startHour: 8.0,
    endHour: 9.733,
    dayIndex: 0,
    startTimeLabel: "8:00 AM",
    color: "blue",
    icon: "car",
    workOrderId: "00048",
    durationHours: 1.73,
  },
  {
    id: "b3a",
    resourceId: "r2",
    title: "Smarthome consulting",
    type: "Requirement",
    durationLabel: "1h 30m",
    startHour: 9.5,
    endHour: 11.0,
    dayIndex: 0,
    startTimeLabel: "9:30 AM",
    color: "light-blue",
    icon: "plug",
    workOrderId: "00049",
    durationHours: 1.5,
  },
  {
    id: "b3b",
    resourceId: "r2",
    title: "Home Improvement",
    type: "Work Order",
    durationLabel: "2h 00m",
    startHour: 9.0,
    endHour: 11.0,
    dayIndex: 1,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "wrench",
    workOrderId: "00052",
    durationHours: 2.0,
  },
  {
    id: "b3c",
    resourceId: "r2",
    title: "00110",
    type: "Work Order",
    durationLabel: "8h 30m",
    startHour: 8.0,
    endHour: 16.5,
    dayIndex: 2,
    startTimeLabel: "12:00 AM",
    color: "pink",
    icon: "clock",
    workOrderId: "00110",
    durationHours: 8.5,
  },
  {
    id: "b3d",
    resourceId: "r2",
    title: "00104",
    type: "Work Order",
    durationLabel: "8h 30m",
    startHour: 9.0,
    endHour: 17.5,
    dayIndex: 3,
    startTimeLabel: "9:00 AM",
    color: "pink",
    icon: "clock",
    workOrderId: "00104",
    durationHours: 8.5,
  },
  {
    id: "b3e",
    resourceId: "r2",
    title: "Printer Installation",
    type: "Work Order",
    durationLabel: "8h 00m",
    startHour: 9.0,
    endHour: 17.0,
    dayIndex: 4,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "plug",
    workOrderId: "00060",
    durationHours: 8.0,
  },

  // Maria Campbell
  {
    id: "b4",
    resourceId: "r3",
    title: "Deliver Packages",
    type: "Requirement",
    durationLabel: "1h 47m",
    startHour: 8.0,
    endHour: 9.783,
    dayIndex: 0,
    startTimeLabel: "8:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00106",
    durationHours: 1.78,
  },
  {
    id: "b4a",
    resourceId: "r3",
    title: "00110",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 12.0,
    endHour: 13.0,
    dayIndex: 0,
    startTimeLabel: "12:00 PM",
    color: "light-blue",
    icon: "clock",
    workOrderId: "00110",
    durationHours: 1.0,
  },
  {
    id: "b5",
    resourceId: "r3",
    title: "Preventive Maintenance",
    type: "Requirement",
    durationLabel: "7h 30m",
    startHour: 9.0,
    endHour: 16.5,
    dayIndex: 1,
    startTimeLabel: "9:00 AM",
    color: "pink",
    icon: "clock",
    workOrderId: "00117",
    durationHours: 7.5,
  },
  {
    id: "b6",
    resourceId: "r3",
    title: "Preventive Maintenance",
    type: "Requirement",
    durationLabel: "3h 00m",
    startHour: 8.0,
    endHour: 11.0,
    dayIndex: 2,
    startTimeLabel: "9:00 AM",
    color: "pink",
    icon: "wrench",
    workOrderId: "00130",
    durationHours: 3.0,
  },
  {
    id: "b6a",
    resourceId: "r3",
    title: "Install soundbar work",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 12.0,
    endHour: 13.0,
    dayIndex: 2,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "plug",
    workOrderId: "00131",
    durationHours: 1.0,
  },
  {
    id: "b7",
    resourceId: "r3",
    title: "00110",
    type: "Work Order",
    durationLabel: "3h 00m",
    startHour: 9.0,
    endHour: 12.0,
    dayIndex: 3,
    startTimeLabel: "9:00 AM",
    color: "light-blue",
    icon: "clock",
    workOrderId: "00110",
    durationHours: 3.0,
  },
  {
    id: "b7a",
    resourceId: "r3",
    title: "Tiles replacement",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 9.0,
    endHour: 10.0,
    dayIndex: 3,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "wrench",
    workOrderId: "00132",
    durationHours: 1.0,
  },
  {
    id: "b7b",
    resourceId: "r3",
    title: "00110",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 5,
    startTimeLabel: "9:00 AM",
    color: "light-blue",
    icon: "clock",
    workOrderId: "00110",
    durationHours: 0.5,
  },

  // Nancy Anderson
  {
    id: "b8",
    resourceId: "r4",
    title: "Fix Boiler",
    type: "Requirement",
    durationLabel: "1h 26m",
    startHour: 9.0,
    endHour: 10.43,
    dayIndex: 0,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "wrench",
    workOrderId: "00114",
    durationHours: 1.43,
  },
  {
    id: "b8a",
    resourceId: "r4",
    title: "00107",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 9.5,
    endHour: 10.5,
    dayIndex: 0,
    startTimeLabel: "9:30 AM",
    color: "light-blue",
    icon: "clock",
    workOrderId: "00107",
    durationHours: 1.0,
  },
  {
    id: "b9",
    resourceId: "r4",
    title: "Tiles replacement",
    type: "Requirement",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 1,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00118",
    durationHours: 0.5,
  },
  {
    id: "b9a",
    resourceId: "r4",
    title: "Install soundbar",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 9.5,
    endHour: 10.5,
    dayIndex: 1,
    startTimeLabel: "9:30 AM",
    color: "light-blue",
    icon: "plug",
    workOrderId: "00119",
    durationHours: 1.0,
  },
  {
    id: "b9b",
    resourceId: "r4",
    title: "AC repair",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 9.0,
    endHour: 10.0,
    dayIndex: 2,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "wrench",
    workOrderId: "00120",
    durationHours: 1.0,
  },
  {
    id: "b9c",
    resourceId: "r4",
    title: "Repair heating unit",
    type: "Work Order",
    durationLabel: "7h 30m",
    startHour: 9.5,
    endHour: 17.0,
    dayIndex: 3,
    startTimeLabel: "9:30 AM",
    color: "pink",
    icon: "wrench",
    workOrderId: "00121",
    durationHours: 7.5,
  },
  {
    id: "b9d",
    resourceId: "r4",
    title: "00105",
    type: "Work Order",
    durationLabel: "2h 30m",
    startHour: 9.0,
    endHour: 11.5,
    dayIndex: 4,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00105",
    durationHours: 2.5,
  },

  // Patrick Sands
  {
    id: "b10",
    resourceId: "r5",
    title: "Install Mount",
    type: "Requirement",
    durationLabel: "3h 22m",
    startHour: 8.0,
    endHour: 11.367,
    dayIndex: 0,
    startTimeLabel: "8:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00134",
    durationHours: 3.37,
  },
  {
    id: "b10a",
    resourceId: "r5",
    title: "lawn care",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 0,
    startTimeLabel: "9:00 AM",
    color: "green",
    icon: "wrench",
    workOrderId: "00135",
    durationHours: 0.5,
  },
  {
    id: "b10b",
    resourceId: "r5",
    title: "00108",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 1,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00136",
    durationHours: 0.5,
  },
  {
    id: "b10c",
    resourceId: "r5",
    title: "Plumber Services",
    type: "Work Order",
    durationLabel: "8h 00m",
    startHour: 9.0,
    endHour: 17.0,
    dayIndex: 2,
    startTimeLabel: "9:00 AM",
    color: "pink",
    icon: "wrench",
    workOrderId: "00137",
    durationHours: 8.0,
  },
  {
    id: "b10d",
    resourceId: "r5",
    title: "Soundproofing",
    type: "Work Order",
    durationLabel: "7h 30m",
    startHour: 9.0,
    endHour: 16.5,
    dayIndex: 3,
    startTimeLabel: "9:00 AM",
    color: "pink",
    icon: "plug",
    workOrderId: "00138",
    durationHours: 7.5,
  },
  {
    id: "b10e",
    resourceId: "r5",
    title: "Soundproofing",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 4,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "plug",
    workOrderId: "00139",
    durationHours: 0.5,
  },

  // Paul Cannon
  {
    id: "b11",
    resourceId: "r6",
    title: "00106",
    type: "Requirement",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 0,
    startTimeLabel: "9:00 AM",
    color: "green",
    icon: "clock",
    workOrderId: "00106",
    durationHours: 0.5,
  },
  {
    id: "b11a",
    resourceId: "r6",
    title: "Preventive Maint.",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 1,
    startTimeLabel: "9:00 AM",
    color: "green",
    icon: "clock",
    workOrderId: "00140",
    durationHours: 0.5,
  },
  {
    id: "b11b",
    resourceId: "r6",
    title: "Soundproofing work",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 2,
    startTimeLabel: "9:00 AM",
    color: "green",
    icon: "plug",
    workOrderId: "00141",
    durationHours: 0.5,
  },
  {
    id: "b11c",
    resourceId: "r6",
    title: "Landscaping",
    type: "Work Order",
    durationLabel: "30m",
    startHour: 9.0,
    endHour: 9.5,
    dayIndex: 4,
    startTimeLabel: "9:00 AM",
    color: "green",
    icon: "wrench",
    workOrderId: "00142",
    durationHours: 0.5,
  },

  // Rene Valdes
  {
    id: "b12",
    resourceId: "r7",
    title: "Install Projector",
    type: "Requirement",
    durationLabel: "3h 22m",
    startHour: 8.0,
    endHour: 11.367,
    dayIndex: 0,
    startTimeLabel: "8:00 AM",
    color: "blue",
    icon: "clock",
    workOrderId: "00125",
    durationHours: 3.37,
  },
  {
    id: "b12b",
    resourceId: "r7",
    title: "Calibrate System",
    type: "Work Order",
    durationLabel: "1h 00m",
    startHour: 12.0,
    endHour: 13.0,
    dayIndex: 2,
    startTimeLabel: "12:00 PM",
    color: "light-blue",
    icon: "wrench",
    workOrderId: "00126",
    durationHours: 1.0,
  },

  // Robert Lyon
  {
    id: "b13",
    resourceId: "r8",
    title: "Install Bookshelf",
    type: "Requirement",
    durationLabel: "3h 00m",
    startHour: 8.5,
    endHour: 11.5,
    dayIndex: 1,
    startTimeLabel: "8:30 AM",
    color: "light-blue",
    icon: "wrench",
    workOrderId: "00158",
    durationHours: 3.0,
  },
  {
    id: "b13a",
    resourceId: "r8",
    title: "Network Wiring",
    type: "Work Order",
    durationLabel: "2h 00m",
    startHour: 10.0,
    endHour: 12.0,
    dayIndex: 3,
    startTimeLabel: "10:00 AM",
    color: "blue",
    icon: "plug",
    workOrderId: "00159",
    durationHours: 2.0,
  },

  // Saurabh Raj
  {
    id: "b14",
    resourceId: "r9",
    title: "Network Setup",
    type: "Work Order",
    durationLabel: "2h 30m",
    startHour: 9.0,
    endHour: 11.5,
    dayIndex: 0,
    startTimeLabel: "9:00 AM",
    color: "blue",
    icon: "plug",
    workOrderId: "00201",
    durationHours: 2.5,
  },
  {
    id: "b14a",
    resourceId: "r9",
    title: "Server Config",
    type: "Work Order",
    durationLabel: "1h 59m",
    startHour: 13.0,
    endHour: 14.983,
    dayIndex: 4,
    startTimeLabel: "1:00 PM",
    color: "grey",
    icon: "clock",
    isDashed: true,
    durationHours: 1.98,
  },
];

// ─── Open Requirements ────────────────────────────────────────────────────────
export const OPEN_REQUIREMENTS: OpenRequirement[] = [
  {
    id: "req1",
    name: "New Lawn",
    fromDate: "9/12/2020",
    toDate: "9/14/2020",
    duration: "16 hrs",
    proposedDuration: "0 mins",
    fulfilledDuration: "15 hrs",
    remaining: "1 hr",
    priority: "",
    territory: "",
    status: "Active",
    createdOn: "9/14/2020 8:03 PM",
  },
  {
    id: "req2",
    name: "Pick Up Trash",
    fromDate: "18/11/2020",
    toDate: "28/11/2020",
    duration: "16 hrs",
    proposedDuration: "0 mins",
    fulfilledDuration: "15 hrs",
    remaining: "1 hr",
    priority: "",
    territory: "",
    status: "Active",
    createdOn: "9/14/2020 8:03 PM",
  },
  {
    id: "req3",
    name: "New Lawn",
    fromDate: "9/12/2020",
    toDate: "9/14/2020",
    duration: "1 hr 59 mins",
    proposedDuration: "0 mins",
    fulfilledDuration: "0 mins",
    remaining: "1 hr 59 mins",
    priority: "",
    territory: "",
    status: "Active",
    createdOn: "9/14/2020 8:00 PM",
  },
  {
    id: "req4",
    name: "Install Bookshelf",
    fromDate: "",
    toDate: "",
    duration: "3 hrs",
    proposedDuration: "0 mins",
    fulfilledDuration: "0 mins",
    remaining: "3 hrs",
    priority: "",
    territory: "",
    status: "Active",
    createdOn: "9/14/2020 8:01 PM",
  },
  {
    id: "req5",
    name: "Pick Up Trash",
    fromDate: "",
    toDate: "",
    duration: "1 hr 30 mins",
    proposedDuration: "0 mins",
    fulfilledDuration: "0 mins",
    remaining: "1 hr 30 mins",
    priority: "",
    territory: "",
    status: "Active",
    createdOn: "9/14/2020 8:02 PM",
  },
];

export const REQUIREMENTS: Requirement[] = [
  {
    id: "req1",
    name: "00045",
    duration: "40 hrs",
    fromDate: "",
    toDate: "",
    territory: "WA",
    priority: "",
    status: "Active",
  },
  {
    id: "req2",
    name: "New Lawn",
    duration: "1 hr 59 mins",
    fromDate: "9/12/2020",
    toDate: "9/14/2020",
    territory: "",
    priority: "",
    status: "Active",
  },
  {
    id: "req3",
    name: "Install Bookshelf",
    duration: "3 hrs",
    fromDate: "",
    toDate: "",
    territory: "",
    priority: "",
    status: "Active",
  },
  {
    id: "req4",
    name: "Pick Up Trash",
    duration: "1 hr 30 mins",
    fromDate: "",
    toDate: "",
    territory: "",
    priority: "",
    status: "Active",
  },
  {
    id: "req5",
    name: "Mow Lawn",
    duration: "2 hrs",
    fromDate: "",
    toDate: "",
    territory: "WA",
    priority: "",
    status: "Active",
  },
  {
    id: "req6",
    name: "Repair Fence",
    duration: "1 hr",
    fromDate: "",
    toDate: "",
    territory: "WA",
    priority: "",
    status: "Active",
  },
  {
    id: "req7",
    name: "HVAC Maintenance",
    duration: "4 hrs",
    fromDate: "9/15/2020",
    toDate: "9/18/2020",
    territory: "WA",
    priority: "High",
    status: "Active",
  },
  {
    id: "req8",
    name: "Plumbing Repair",
    duration: "2 hrs 30 mins",
    fromDate: "9/16/2020",
    toDate: "9/17/2020",
    territory: "",
    priority: "Normal",
    status: "Active",
  },
  {
    id: "req9",
    name: "Electrical Work",
    duration: "3 hrs 30 mins",
    fromDate: "",
    toDate: "",
    territory: "",
    priority: "High",
    status: "Active",
  },
  {
    id: "req10",
    name: "Roof Inspection",
    duration: "1 hr",
    fromDate: "",
    toDate: "",
    territory: "WA",
    priority: "",
    status: "Active",
  },
];

// ─── Hourly time slots (7AM–6PM) ──────────────────────────────────────────────
export const TIME_SLOTS: string[] = [
  "7:00 AM",
  "8:00 AM",
  "9:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 PM",
  "1:00 PM",
  "2:00 PM",
  "3:00 PM",
  "4:00 PM",
  "5:00 PM",
  "6:00 PM",
];
export const START_HOUR = 7;

// Default day labels for the 7-day default range (Mon 9/14 – Sun 9/20)
export const DEFAULT_DAY_LABELS: string[] = [
  "Mon 9/14",
  "Tue 9/15",
  "Wed 9/16",
  "Thu 9/17",
  "Fri 9/18",
  "Sat 9/19",
  "Sun 9/20",
];

// Week ranges (for weekly view columns, replicating D365 screenshot 3)
export const WEEK_RANGES: { label: string }[] = [
  { label: "21" },
  { label: "31–6" },
  { label: "7–13" },
  { label: "14–20" },
  { label: "21–27" },
  { label: "28–6" },
  { label: "7–13" },
  { label: "14–20" },
  { label: "21–27" },
];

export const HOUR_WIDTH_PX = 120;
export const DAY_WIDTH_PX = 180;
export const WEEK_WIDTH_PX = 140;

export const BOOKING_STATUSES = [
  "Scheduled",
  "Committed",
  "Canceled",
  "Hard",
] as const;
export const BOOKING_METHODS = [
  "Front Load Hours",
  "Proportional",
  "Override Duration",
] as const;
